name: Build and Export OpenImageIO

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clone vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && git checkout ca1501f4b2cbc0a502594db6f303622394dbdf9f && .\bootstrap-vcpkg.bat

    - name: Install OpenImageIO
      run: |
        .\vcpkg\vcpkg.exe install openimageio[gif,libheif,libraw,opencolorio,openjpeg,pybind11,tools]:x64-windows

    - name: Export OpenImageIO as Zip
      run: |
        .\vcpkg\vcpkg.exe export openimageio:x64-windows --zip --output-dir artifacts
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openimageio-package
        path: artifacts/*.zip
